#Description:
#  本地代价地图需要配置的参数，各参数意义如下:
#  global_frame:在本地代价地图中的全局坐标系;
#  robot_base_frame:机器人本体的基坐标系;

local_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 10.0 #3.5 #3.0 #update frequency for planning
  publish_frequency: 4.0 #publish frequency for rviz
#  static_map: true
  rolling_window: true
  width: 2.5 #3.5
  height: 2.5 #3.5
  resolution: 0.05
  transform_tolerance: 10
  plugins:
    - {name: static_layer,    type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer,  type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
#    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
