TebLocalPlannerROS:
  odom_topic: odom
  map_frame: /map

  ############运动学限制############
  acc_lim_x: 0.3 #2.5 # $ 1.5135 2.5 3.2 0.8 1.0 1.2 
  acc_lim_y: 0.3 # $
  acc_lim_theta: 2.1 #2.07 4.5 3.65 5.89 1.92 2.12* or 2.32* 3.42 3.67yyy 4.67
  max_vel_x: 0.7 #1.0 #1.0 # $ 0.6642 #0.5472 1.1 0.8 0.3172 0.3572bucuo 0.3972yebucuo 0.4172 0.4372 0.7442y
  max_vel_y: 0.7 #1.0 #0.8 # $ 0.22 #0.3 0.1 0.2 0.25*
  max_vel_x_backwards: 0.3 #0.15 #0.1 #1.1
  max_vel_theta: 2.4 #3.5 # $ 1.7 #2.75 0.5 0.75 0.801.53y latest:1.68  10.7
  min_turning_radius: 0.0 #0.15 #0.01 0.1
  is_footprint_dynamic: true #false
  footprint_model:
    type: "polygon" #"line" #"polygon"
#    line_start: [-0.119,0]
#    line_end: [0.119,0]
    vertices: [[0.171, -0.125], [0.171, 0.125], [-0.171, 0.125], [-0.171, -0.125]] 
    #[[0.171, -0.128], [0.171, 0.128],[-0.171, 0.128], [-0.171, -0.128]]
  ##################################

  ############目标和轨迹############
  yaw_goal_tolerance: 0.18 #0.2 newest:0.1
  xy_goal_tolerance: 0.4 #0.2 #0.1 newest:0.5
  free_goal_vel: false #true #false
  complete_global_plan: false # true
  dt_ref: 0.6 #0.3 latest:0.2
  dt_hysteresis: 0.06 #0.1 0.03 0.1 latest:0.02
  global_plan_overwrite_orientation: true  #false(good start but lack rotation)
  global_plan_viapoint_sep: 0.05 #0.07  #-0.1
  max_global_plan_lookahead_dist: 0.55 #0.55 #0.84 #1.1 #2.2* 1.5** latest:0.555
  force_reinit_new_goal_dist: 0.1 #0.20
  feasibility_check_no_poses: 1  #2
  publish_feedback: false
  allow_init_with_backwards_motion: false
  exact_arc_length: true
  shrink_horizon_backup: true
  shrink_horizon_min_duration: 5.0 #10.0
  ##################################

  ############障碍物相关############
  min_obstacle_dist: 0.10 #0.18 #0.2  #0.18  #0.15 0.01 latest:0.11
  include_costmap_obstacles: true
  costmap_obstacles_behind_robot_dist: 1.0
  inflation_dist: 0.25 #0.5 #0.6
  include_dynamic_obstacles: true #false
  legacy_obstacle_association: false
  obstacle_association_force_inclusion_factor: 0.1 #1.5
  obstacle_association_cutoff_factor: 6
  obstacle_poses_affected: 7
  costmap_converter_plugin: "costmap_converter::CostmapToLinesDBSRANSAC"
  costmap_converter_spin_thread: true
  costmap_converter_rate: 5 #5.0 3.5*(?)
  ##################################

  ############优化相关参数############
  no_inner_iterations: 3 #5
  no_outer_iterations: 4 #4
  #到达速度限制之前让小车提前减速的参数（可以按pid去理解，使车越靠近目标点越减速），极性和范围待定
  #现在看来好像调小一些会顺滑
  penalty_epsilon: 0.1 #0.005 #0.05 #0.11 0.09 0.05*
  #整个运动过程中主要是以低速还是高速运行，由下面六个参数决定。m_v_x和m_v_y范围0~2，其他0~1，极性待定
  obstacle_cost_exponent: 4.0 #22.7.24 new add in
  weight_acc_lim_x: 2.0 #3.1623 #1.0
  weight_acc_lim_y: 2.0
  weight_acc_lim_theta: 10.0 #10.0 #10.0 #1.0 1.4 5.0 10.0*
  weight_max_vel_x: 5.0 #2.0
  weight_max_vel_y: 5.0 #10.0 
  weight_max_vel_theta: 10.0 #10.0 #100.0 #1.0 1000.0
  #迫使小车选择x方向的权重，越大越不容易横移
  weight_kinematics_nh: 9.4 #90.0 #1.0 #1000.0
  #迫使机器人只选择前进方向的权重，越大越抑制倒车，范围0~1000
  weight_kinematics_forward_drive: 1000.0
  #小车最小转弯半径的权重，越大小车越容易达到最小转弯半径，范围0~1000
  weight_kinematics_turning_radius: 1.5 #1.0 15.0 100.0 80wwwww # 20220721 before backup I was adjusting this parameter.
  #越大时小车就会在直道上快速加速并且压内弯，范围0~1000
  weight_optimaltime: 7.9 #8.0 #10.0 #6.0 #1.5 #4.5  #525.8 1.0 52.3  26.19 8.12 4.12 6.12*
  weight_obstacle: 2.8 #55.0 #280 #500.0 #1000.0 #0.1 #50.0 #100.0 90.9
  weight_viapoint: 1.8  #360 #550.0 #700.0 #1.0 80
  weight_inflation: 0.75 #65.0 #200.0 #0.1 0.8*
  weight_shortest_path: 0.0
  weight_adapt_factor: 2.0
  #########################################

  enable_homotopy_class_planning: false #true 
  enable_multithreading: true #false
  max_number_classes: 2
  selection_cost_hysteresis: 1.0
  selection_obst_cost_scale: 1.0 #50.0
  selection_viapoint_cost_scale: 2.0
  selection_alternative_time_cost: false
  roadmap_graph_no_samples: 6 #15
  roadmap_graph_area_width: 5
  h_signature_prescaler: 1.0
  h_signature_threshold: 0.1
  obstacle_heading_threshold: 0.45
  visualize_hc_graph: false
  viapoints_all_candidates: true #false
  switching_blocking_period: 0.0
  
  detours_orientation_tolerance : M_PI / 1.0
  delete_detours_backwards : false
  length_start_orientation_vector : 0.8
  max_ratio_detours_duration_best_duration : 0.5
