#Description:
#  全局代价地图参数配置文件,各参数的意义如下：
#  global_frame:在全局代价地图中的全局坐标系;
#  robot_base_frame:机器人的基坐标系;
#
global_costmap:
  global_frame: map # 要在其中运行的成本图的全球框架
  robot_base_frame: base_link # 机器人基本链接的框架名称
  update_frequency: 0.5 # 要更新的地图的频率（以 Hz 为单位）
  publish_frequency: 0.5 # 要发布的地图显示信息的频率（以 Hz 为单位）
  # static_map: true
  rolling_window: false # 是否使用成本图的滚动窗口版本，如果static_map参数设置为 true，则必须将此参数设置为 false
  transform_tolerance: 10 # 指定转换 （tf） 数据中可容忍的延迟（以秒为单位）
  track_unknown_space: true
  plugins:
#插件规范序列，每层一个。每个规范都是一个包含名称和类型字段的字典。该名称用于定义插件的参数命名空间。
    - {name: static_layer,    type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer,  type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
    