#Description:
#   * allow_unknown:是否允许规划器规划穿过未知区域的路径,
#        只设计该参数为true还不行,还要在costmap_commons_params.yaml
#        中设置track_unknown_space参数也为true才行.
#   * default_tolerance:当设置的目的地被障碍物占据时,需要以该参数
#        为半径寻找到最近的点作为新目的地点.
#   * visualize_potential:是否显示从PointCloud2计算得到的势区域.
#   * use_dijkstra:设置为true,将使用dijkstra算法,否则使用A*算法.
#   * use_quadratic:设置为true,将使用二次函数近似函数,否则使用更加
#      简单的计算方式,这样节省硬件计算资源.
#   * use_grid_path:如果设置为true,则会规划一条沿着网格边界的路径,
#      偏向于直线穿越网格,否则将使用梯度下降算法,路径更为光滑点.
#   * old_navfn_behavior:若在某些情况下,想让global_planner完全复制navfn
#      的功能,那就设置为true,但是需要注意navfn是非常旧的ROS系统中使用的,
#      现在已经都用global_planner代替navfn了,所以不建议设置为true.
#   * lethal_cost:致命代价值,默认是设置为253,可以动态来配置该参数.
#   * neutral_cost:中等代价值,默认设置是50,可以动态配置该参数.
#   * cost_factor:代价地图与每个代价值相乘的因子.
#   * publish_potential:是否发布costmap的势函数.
#   * orientation_mode: 如何设置每个点的方向（None = 0,Forward = 1,
#       Interpolate = 2,ForwardThenInterpolate = 3,Backward = 4,
#       Leftward = 5,Rightward = 6）（可动态重新配置）
#   * orientation_window_size:根据orientation_mode指定的位置积分来得到
#      使用窗口的方向.默认值1,可以动态重新配置.
GlobalPlanner:
  allow_unknown: true # 原为f，指定是否允许规划器创建遍历未知空间的计划
  default_tolerance: 0.0 # 当设置的目的地被障碍物占据时,需要以该参数为半径寻找到最近的点作为新目的地点.
  visualize_potential: false # 指定是否可视化通过 PointCloud2 计算的潜在区域
  use_dijkstra: true # 如果为 true，则使用 dijkstra 算法。否则为 A*
  use_quadratic: true # 原为false。如果为 true，则使用势的二次近似；否则，请使用更简单的计算
  use_grid_path: false # 如果为 true，则创建遵循格网边界的路径。否则，请使用梯度下降方法。
  old_navfn_behavior: false # 若希望global_planner完全镜像 navfn 的行为，则设为true

  lethal_cost: 253 # 致命代价（动态重新配置）
  neutral_cost: 66   #之前 50。中性成本（动态重新配置）
  cost_factor: 0.5 #之前 1。将成本图中每个成本乘以（动态重新配置）的系数
  publish_potential: true # 发布潜在成本图（动态重新配置）
  orientation_mode: 1 # 如何设置每个点的方向（无=0，向前=1，插值=2，向前然后插值=3，向后=4，向左=5，向右=6）（动态重新配置）
  orientation_window_size: 1 # 使用什么窗口根据方向模式指定的仓位导数确定方向（动态重新配置）

                                                                                                          